apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: env, operator: In, values: [production]}
      - {key: country, operator: In, values: [us]}
  template:
    metadata:
      name: myweb-pod 
      labels: 
        env: production
        country: us
    spec:
      containers:
        - name: myweb-con
          image: httpd        
        